language: cpp
dist: trusty
notifications:
  email: false
before_install:
- sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
- gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
- gpg -a --export E084DAB9 | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install -y cmake libboost-dev libboost-system-dev libboost-filesystem-dev libnuma-dev libaio-dev libhwloc-dev libatlas-base-dev zlib1g-dev numactl
- sudo apt-get install -y r-base-core
compiler:
- g++
script:
- mkdir -p build && cd build && cmake .. && make && cd ..
- make clean; make
- cd libsafs/unit-test && make test && cd ../..
- cd flash-graph/unit-test && make test
- cd ../release-test/ && ./run_release_test.sh
- cd ../..
- cd matrix/unit-test && make test && cd ../..
