language: cpp
dist: trusty
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get install -y cmake libboost-dev libboost-system-dev libboost-filesystem-dev libnuma-dev libaio-dev libhwloc-dev libatlas-base-dev zlib1g-dev
compiler:
- g++
script:
- make clean; make
- cd libsafs/unit-test && make test && cd ../..
- cd flash-graph/unit-test && make test
- cd ../release-test/ && ./run_release_test.sh
- cd ../..
- cd matrix/unit-test && make test && cd ../..
